import type { Metadata } from "next";
import "./globals.css";
import App from "@/component/App";
import { EB_Garamond } from "next/font/google"; // Import EB Garamond from Google Fonts

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
  weight: ["400", "700"], // Add weights you plan to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: ebGaramond.style.fontFamily, backgroundColor: "white" , color: "black" }}>
        <App />
        {children}
      </body>
    </html>
  );
}